/**
 * ProjectView — a project is a collection of councils and chats. This view lists
 * the project's councils and chats in tables, plus the artifacts their councils
 * generated. Councils/chats can be added to (and removed from) the project here.
 */
import { useEffect, useState, type FC } from 'react';
import { councilStore } from '../council';
import { getAllOutputs } from '../council/context-store';
import {
  getProject,
  useProjects,
  renameProject,
  addCouncilToProject,
  removeCouncilFromProject,
  addChatToProject,
  removeChatFromProject,
  getProjectForCouncil,
  getProjectForChat,
} from '../services/projectsStore';
import './ProjectView.css';

interface ChatLite { id: string; title: string }

interface ProjectViewProps {
  projectId: string;
  chats: ChatLite[];
  onOpenCouncil: (id: string) => void;
  onOpenChat: (id: string) => void;
}

const ProjectView: FC<ProjectViewProps> = ({ projectId, chats, onOpenCouncil, onOpenChat }) => {
  useProjects(); // re-render on project changes
  const [, force] = useState(0);
  useEffect(() => councilStore.subscribe(() => force((n) => n + 1)), []);
  const [addingCouncil, setAddingCouncil] = useState(false);
  const [addingChat, setAddingChat] = useState(false);

  const project = getProject(projectId);
  if (!project) {
    return <div className="project-view"><div className="pv-empty">Project not found.</div></div>;
  }

  const allCouncils = councilStore.getAll();
  const projectCouncils = project.councilIds
    .map((id) => allCouncils.find((c) => c.id === id))
    .filter(Boolean) as ReturnType<typeof councilStore.getAll>;
  const projectChats = project.chatIds
    .map((id) => chats.find((c) => c.id === id))
    .filter(Boolean) as ChatLite[];

  // Councils available to add: standalone anchors, not pipeline-generated, unassigned.
  const addableCouncils = allCouncils.filter(
    (c) => !c.pipelineId && (!c.workflowId || (c.workflowOrder ?? 0) === 0) && !getProjectForCouncil(c.id)
  );
  const addableChats = chats.filter((c) => !getProjectForChat(c.id));

  // Artifacts generated by this project's councils.
  const artifacts = projectCouncils.flatMap((c) =>
    getAllOutputs(c.id).map((o) => ({ councilId: c.id, councilName: c.workflowName || c.name, version: o.version, content: o.content }))
  );

  const fmtDate = (s: string) => new Date(s).toLocaleDateString(undefined, { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });

  return (
    <div className="project-view">
      <div className="pv-header">
        <input
          className="pv-name"
          defaultValue={project.name}
          onBlur={(e) => { if (e.target.value.trim() && e.target.value !== project.name) renameProject(project.id, e.target.value.trim()); }}
        />
        <span className="pv-sub">{projectCouncils.length} councils · {projectChats.length} chats · {artifacts.length} artifacts</span>
      </div>

      {/* Councils */}
      <div className="pv-section">
        <div className="pv-section-head">
          <h3>Councils</h3>
          <button className="pv-add-btn" onClick={() => setAddingCouncil((v) => !v)}>+ Add council</button>
        </div>
        {addingCouncil && (
          <div className="pv-picker">
            {addableCouncils.length === 0 ? <span className="pv-picker-empty">No unassigned councils.</span> :
              addableCouncils.map((c) => (
                <button key={c.id} className="pv-picker-item" onClick={() => { addCouncilToProject(project.id, c.id); setAddingCouncil(false); }}>
                  {c.workflowName || c.name}
                </button>
              ))}
          </div>
        )}
        {projectCouncils.length === 0 ? (
          <div className="pv-empty">No councils in this project yet.</div>
        ) : (
          <div className="council-table">
            <div className="council-table-head">
              <span className="ct-col ct-name">Name</span>
              <span className="ct-col ct-status">Status</span>
              <span className="ct-col ct-agents">Agents</span>
              <span className="ct-col ct-updated">Updated</span>
              <span className="ct-col pv-rowactions" />
            </div>
            {projectCouncils.map((c) => {
              const steps = councilStore.getWorkflow(c.id).length;
              return (
                <div key={c.id} className="council-row pv-council-row">
                  <span className="ct-col ct-name">{c.workflowName || c.name}{steps > 1 && <span className="ct-steps">{steps} steps</span>}</span>
                  <span className="ct-col ct-status"><span className="crd-role">{c.status}</span></span>
                  <span className="ct-col ct-agents">{c.personas.length}</span>
                  <span className="ct-col ct-updated">{fmtDate(c.updatedAt)}</span>
                  <span className="ct-col pv-rowactions">
                    <button className="council-action" onClick={() => onOpenCouncil(c.id)}>Open</button>
                    <button className="council-action" onClick={() => removeCouncilFromProject(c.id)}>Remove</button>
                  </span>
                </div>
              );
            })}
          </div>
        )}
      </div>

      {/* Chats */}
      <div className="pv-section">
        <div className="pv-section-head">
          <h3>Chats</h3>
          <button className="pv-add-btn" onClick={() => setAddingChat((v) => !v)}>+ Add chat</button>
        </div>
        {addingChat && (
          <div className="pv-picker">
            {addableChats.length === 0 ? <span className="pv-picker-empty">No unassigned chats.</span> :
              addableChats.map((c) => (
                <button key={c.id} className="pv-picker-item" onClick={() => { addChatToProject(project.id, c.id); setAddingChat(false); }}>
                  {c.title || 'Untitled chat'}
                </button>
              ))}
          </div>
        )}
        {projectChats.length === 0 ? (
          <div className="pv-empty">No chats in this project yet.</div>
        ) : (
          <div className="council-table">
            {projectChats.map((c) => (
              <div key={c.id} className="council-row pv-chat-row">
                <span className="ct-col ct-name">{c.title || 'Untitled chat'}</span>
                <span className="ct-col pv-rowactions">
                  <button className="council-action" onClick={() => onOpenChat(c.id)}>Open</button>
                  <button className="council-action" onClick={() => removeChatFromProject(c.id)}>Remove</button>
                </span>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Artifacts */}
      <div className="pv-section">
        <div className="pv-section-head"><h3>Artifacts</h3></div>
        {artifacts.length === 0 ? (
          <div className="pv-empty">No generated artifacts yet — they appear as the project's councils produce output.</div>
        ) : (
          <div className="pv-artifacts">
            {artifacts.map((a, i) => (
              <button key={i} className="pv-artifact" onClick={() => onOpenCouncil(a.councilId)}>
                <div className="pv-artifact-head">
                  <span className="pv-artifact-name">{a.councilName}</span>
                  <span className="pv-artifact-ver">v{a.version}</span>
                </div>
                <div className="pv-artifact-snippet">{(a.content || '').slice(0, 240)}</div>
              </button>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default ProjectView;
